name: Continuous Integration

on: [pull_request]

jobs:
  check:
    name: 🔎 Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Format code
        run: yarn format --write .

      - name: Check format
        run: yarn format:check

  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test --watchAll=false

  build:
    name: 👷🏼‍♂️ Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
